version: '3'

services:
  dns:
     image: mvance/unbound:latest
     volumes:
       - ${PWD}/dns.conf:/opt/unbound/etc/unbound/unbound.conf:ro
       - ${PWD}/certs:/opt/unbound/etc/unbound/certs
     network_mode: host
     restart: always

  exporter:
     image: egguy/unbound-prometheus-exporter:latest
     volumes:
       - ${PWD}/dns.conf:/etc/unbound/unbound.conf:ro
       - ${PWD}/certs:/etc/unbound/
     network_mode: host
     restart: always

